import Head from "next/head";
import { useState } from "react";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

import NavBar from "@/components/layout/nav/NavBar";
import { CustomControls } from "@/components/layout/nav/SlideControl";
import { Hero, About, Techs, Places } from "@/components/modules";

import { FullPage, Slide } from "react-full-page";

export default function Home() {
  const slidesToInvert = [2];
  const initialSlide = 0;

  const [activeSlider, setActiveSlider] = useState(initialSlide);

  return (
    <>
      <Head>
        <title>Felipe Boni</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar sliderProps={{ slidesToInvert, activeSlider }} />

      <FullPage
        controls={CustomControls}
        controlsProps={{
          className: "fixed z-[999] bottom-10 right-10 flex flex-col gap-1",
          slidesToInvert,
        }}
        beforeChange={({ to }) => setActiveSlider(to)}
        initialSlide={initialSlide}
      >
        <Slide>
          <Hero />
        </Slide>
        <Slide>
          <About />
        </Slide>
        <Slide>
          <Techs />
        </Slide>
        <Slide>
          <Places />
        </Slide>
      </FullPage>
    </>
  );
}
