import Head from 'next/head'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] });

import NavBar from "@/components/layout/nav/NavBar";
import { Hero } from "@/components/modules"

export default function Home() {
  return (
    <>
      <Head>
        <title>Felipe Boni</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link href="https://fonts.cdnfonts.com/css/le-murmure" rel="stylesheet"/>
      </Head>

      <NavBar/>

      <main>
        <Hero/>
      </main>
    </>
  )
}
