import Head from "next/head";
import { useState } from "react";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

import NavBar from "@/components/layout/nav/NavBar";
import { CustomControls } from "@/components/layout/nav/SlideControl";
import { Hero, About, Techs, Places, Featured } from "@/components/modules";

import { FullPage, Slide } from "react-full-page";
import { BrowserView, MobileView } from "react-device-detect";

export default function Home() {
  const slidesToInvert = [];
  const initialSlide = 0;

  const [activeSlider, setActiveSlider] = useState(initialSlide);

  return (
    <>
      <Head>
        <title>Felipe Boni</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MobileView>
        <div className="flex flex-col items-center justify-center h-screen gap-3 px-8 text-center">
          <h1 className="text-3xl font-semibold">Ops!</h1>

          <span className="text-xl">For now, this portfolio is not available for mobile.</span>
          <span className="opacity-50">Open on the browser to view.</span>
        </div>
      </MobileView>
          
      <BrowserView>
        <NavBar sliderProps={{ slidesToInvert, activeSlider }} />

        <FullPage
          controls={CustomControls}
          controlsProps={{
            className: "fixed z-[999] bottom-24 right-24 flex flex-col gap-1",
            slidesToInvert,
          }}
          beforeChange={({ to }) => setActiveSlider(to)}
          initialSlide={initialSlide}
        >
          <Slide>
            <Hero />
          </Slide>
          <Slide>
            <About />
          </Slide>
          <Slide>
            <Places />
          </Slide>
          <Slide>
            <Featured />
          </Slide>
        </FullPage>
      </BrowserView>
    </>
  );
}
